Asta = {
    'Name': 'Asta',
    'Owner': 'Asta',
    'Team': 'Black Bulls',
    'Series': 'Black Clover',
    'Type': 'Balanced',
    'Bit Beast': 'Anti-Magic Demon',
    'Generation': 'Clover Gen',
    'HP': 320,
    'ATK': 180,
    'DEF': 100,
    'SPEED': 150,
    'ACCURACY': 0.90,
    'DAMAGE': '15-70',
    'Normal Moves': ['Demon-Slayer Slash', 'Black Meteorite', 'Blade Rush'],
    'Special Moves': ['Black Divider', 'Devil Union Slash'],
    'Element': 'Anti-Magic',
    'Special Trait': 'Nullify all magic-type effects',
    'Rarity': 'Legendary',
    'Pic': 'asta_image_url',
    'Description': "Asta uses anti-magic to overcome all odds. Wielding massive swords and unbreakable resolve, he's a relentless fighter from the Black Bulls."
}

Magna = {
    'Name': 'Magna Swing',
    'Owner': 'Magna',
    'Team': 'Black Bulls',
    'Series': 'Black Clover',
    'Type': 'Attack',
    'Bit Beast': 'Fire Soul',
    'Generation': 'Clover Gen',
    'HP': 280,
    'ATK': 160,
    'DEF': 80,
    'SPEED': 140,
    'ACCURACY': 0.80,
    'DAMAGE': '10-60',
    'Normal Moves': ['Fireball Smash', 'Explosive Strike', 'Burning Charge'],
    'Special Moves': ['Soul Chain Deathmatch', 'Inferno Cyclone'],
    'Element': 'Fire',
    'Special Trait': 'Chains enemy’s HP to his own in 1v1',
    'Rarity': 'Epic',
    'Pic': 'magna_image_url',
    'Description': "Magna fights with explosive fire magic and fearless grit. His new Soul Chain technique makes him a dangerous duelist."
}

Luck = {
    'Name': 'Luck Voltia',
    'Owner': 'Luck',
    'Team': 'Black Bulls',
    'Series': 'Black Clover',
    'Type': 'Speed',
    'Bit Beast': 'Lightning Fiend',
    'Generation': 'Clover Gen',
    'HP': 290,
    'ATK': 150,
    'DEF': 85,
    'SPEED': 180,
    'ACCURACY': 0.88,
    'DAMAGE': '12-65',
    'Normal Moves': ['Lightning Kick', 'Rapid Blitz', 'Volt Rush'],
    'Special Moves': ['Thunder God Boots', 'Lightning Storm Fist'],
    'Element': 'Lightning',
    'Special Trait': 'Speed increases with each turn',
    'Rarity': 'Epic',
    'Pic': 'luck_image_url',
    'Description': "Luck is a battle maniac who loves fighting strong enemies. His lightning magic grants him insane speed and agility in combat."
}