Asta = {
    'Name': 'Asta',
    'Owner': 'Asta',
    'Squad': 'Black Bulls',
    'Series': 'Black Clover',
    'Role': 'Magic Knight',
    'Attribute': 'Anti-Magic',
    'HP': 320,
    'ATK': 180,
    'DEF': 100,
    'SPEED': 150,
    'ACCURACY': 0.90,
    'DAMAGE': '15-70',
    'Normal Moves': ['Demon-Slayer Slash', 'Black Meteorite', 'Rush Strike'],
    'Special Moves': ['Black Divider', 'Devil Union Slash'],
    'Trait': 'Nullifies all magic effects',
    'Rarity': 'Legendary',
    'Pic': 'https://files.catbox.moe/rl43ye.jpg',
    'Description': "Asta, born without magic, uses anti-magic swords and pure determination to defeat powerful foes. His Devil Union form amplifies his strength to a terrifying level."
}

Magna = {
    'Name': 'Magna Swing',
    'Owner': 'Magna',
    'Squad': 'Black Bulls',
    'Series': 'Black Clover',
    'Role': 'Magic Knight',
    'Attribute': 'Fire',
    'HP': 280,
    'ATK': 160,
    'DEF': 85,
    'SPEED': 140,
    'ACCURACY': 0.82,
    'DAMAGE': '10-60',
    'Normal Moves': ['Fireball Strike', 'Exploding Smash', 'Hothead Combo'],
    'Special Moves': ['Soul Chain Deathmatch', 'Blazing Blast'],
    'Trait': 'Can tie HP to opponent for equal battle',
    'Rarity': 'Epic',
    'Pic': 'https://files.catbox.moe/a4r256.jpg',
    'Description': "Magna's fiery spirit burns strong. With his new Soul Chain magic, he can fight even the strongest opponents on equal footing."
}

Luck = {
    'Name': 'Luck Voltia',
    'Owner': 'Luck',
    'Squad': 'Black Bulls',
    'Series': 'Black Clover',
    'Role': 'Magic Knight',
    'Attribute': 'Lightning',
    'HP': 290,
    'ATK': 150,
    'DEF': 90,
    'SPEED': 180,
    'ACCURACY': 0.88,
    'DAMAGE': '12-65',
    'Normal Moves': ['Lightning Jab', 'Thunder Burst', 'Volt Dash'],
    'Special Moves': ['Thunder God Boots', 'Storm Fist Barrage'],
    'Trait': 'Speed increases every turn',
    'Rarity': 'Epic',
    'Pic': 'https://files.catbox.moe/x6cbgl.jpg',
    'Description': "Luck is a cheerful battle junkie who uses lightning-fast attacks to overwhelm enemies. His power increases as the fight drags on."
}